spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: transaction-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/transactions/**,/api/v1/categories/**

server:
  port: 8080

logging:
  group:
    tcp: javax.management.remote, sun.rmi
    servlet: org.springframework.web.servlet.DispatcherServlet
  level:
    root: info
    tcp: info
    servlet: debug
  pattern:
    console: '%d{dd.MM.YYYY HH:mm:ss.SSS} %highlight(%-5level) --- [%25thread] --- %-75logger{75} : %cyan(%msg%n)'