spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: transaction-service
            uri: http://localhost:8081
            predicates:
              - Path=/transactions/**,/categories/**

server:
  port: 8080

frontend:
  uri: http://localhost:5174

logging:
  level:
    root: debug
    tcp: info
  group:
    tcp: javax.management.remote, sun.rmi
  pattern:
    console: '%d{dd.MM.YYYY HH:mm:ss.SSS} %highlight(%-5level) --- [%25thread] --- %-75logger{75} : %cyan(%msg%n)'